### ISSUE TITLE
Is it possible to hide year switching buttons?

### ISSUE THREAD

**Issue by brain545** [weifeiyue/vue-datepicker-local#59]
In my case I need to hide year switching buttons, like
![screenshot_2018-08-13](https://user-images.githubusercontent.com/11940682/44026083-a21797a8-9efa-11e8-8a89-4af70a94f308.png)
Can I do this with **vue-datepicker-local**?

**Comment by weifeiyue** [comment]
you can do it like this:
```css
.calendar-next-decade-btn, .calendar-next-year-btn {
    visibility: hidden;
}
```
